# Generated by Django 4.2.14 on 2024-11-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='yookassa_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
